apiVersion: v1
kind: Pod
metadata:
  name: cm-pod
spec:
  restartPolicy: Always
  containers:
    - name: debug-container
      image: jhansen/k8s-debugger:latest
      imagePullPolicy: Always
      command: [ "/bin/bash", "-c", "sleep 9000"]
      volumeMounts:
        - name: test-cm
          mountPath: /config/test-cm
  volumes:
    - name: test-cm
      configMap:
        name: test-cm
